# Generated by Django 2.1 on 2019-10-22 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vitrine', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.FileField(upload_to='images/')),
                ('nom', models.CharField(max_length=100)),
                ('bio', models.TextField()),
                ('formation', models.TextField()),
                ('engagement', models.TextField()),
                ('fonction', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('linkedin', models.CharField(max_length=100)),
            ],
        ),
    ]
