# Generated by Django 2.1 on 2019-10-24 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vitrine', '0002_equipe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipe',
            name='photo',
            field=models.FileField(upload_to='images'),
        ),
    ]
