# Generated by Django 2.1 on 2019-10-24 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vitrine', '0003_auto_20191024_0839'),
    ]

    operations = [
        migrations.AddField(
            model_name='actualite',
            name='date_publication',
            field=models.DateField(blank=True, null=True),
        ),
    ]
