# Generated by Django 2.1 on 2019-11-06 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vitrine', '0004_actualite_date_publication'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipe',
            name='engagement',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='equipe',
            name='formation',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='equipe',
            name='linkedin',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
